[versions]
activityCompose = "1.12.4"
androidGradlePlugin = "8.13.2"
appcompat = "1.7.0"
compose = "1.7.8"
coreKtx = "1.13.1"
detekt = "1.23.6"
dokka = "1.9.10"
kotlin = "2.0.20"
material3Android = "1.3.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
detekt-plugin = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt"}
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-material3-android = { module = "androidx.compose.material3:material3-android", version.ref = "material3Android" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
dokka-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
tools-gradle = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
